// Browser half of the experimental A320 JIT. Only compilation/registration
// crosses JavaScript; compiled blocks are called directly from Rust/Wasm.
addToLibrary({
  $DingooWasmJit__deps: ['$addFunction', '$removeFunction', '$wasmMemory'],
  $DingooWasmJit__postset: `
    Module['dingooWasmJitStats'] = () => DingooWasmJit.stats();
    Module['dingooWasmJitDispose'] = () => DingooWasmJit.dispose();
  `,
  $DingooWasmJit: {
    sessions: new Map(),
    nextSession: 1,
    nextRequest: 1,
    active: 0,
    scheduled: false,
    disposed: false,
    submitted: 0,
    compiled: 0,
    failed: 0,
    discarded: 0,
    lastError: '',
    limits: {requests: 256, bytes: 1024 * 1024, moduleBytes: 65536, parallel: 2, sessions: 16},

    shared: function() {
      return typeof SharedArrayBuffer !== 'undefined' && HEAPU8.buffer instanceof SharedArrayBuffer;
    },

    create: function() {
      if (this.disposed || Module['dingooWasmJitEnabled'] === false
          || typeof WebAssembly.compile !== 'function'
          || this.sessions.size >= this.limits.sessions || this.nextSession >= 0x7fffffff) return 0;
      var id = this.nextSession++;
      this.sessions.set(id, {generation: 1, bytes: 0, requests: new Map()});
      return id;
    },

    submit: function(id, pointer, length) {
      var session = this.sessions.get(id);
      // Copy before returning: Rust frees its generated byte buffer immediately.
      if (!session || this.disposed || !length || length > this.limits.moduleBytes
          || session.requests.size >= this.limits.requests
          || session.bytes + length > this.limits.bytes || this.nextRequest >= 0x7fffffff
          || pointer < 0 || pointer + length > HEAPU8.length) return 0;
      var token = this.nextRequest++;
      var request = {token: token, session: id, generation: session.generation,
        bytes: HEAPU8.slice(pointer, pointer + length), size: length,
        state: 'queued', result: 0, slot: null};
      session.requests.set(token, request);
      session.bytes += length;
      this.submitted++;
      this.schedule();
      return token;
    },

    live: function(request) {
      var session = this.sessions.get(request.session);
      return !this.disposed && session && session.generation === request.generation
        && session.requests.get(request.token) === request;
    },

    schedule: function() {
      if (this.disposed || this.scheduled) return;
      this.scheduled = true;
      // Defer until the current Wasm stack has returned. A pthread's continuous
      // setImmediate main loop can starve timer tasks in WebKit, so its compiler
      // pump uses microtasks. Keep the existing browser-thread timer behavior.
      // At most two asynchronous compilations are in flight per module.
      const pump = () => { this.scheduled = false; this.pump(); };
      if (typeof ENVIRONMENT_IS_PTHREAD !== 'undefined' && ENVIRONMENT_IS_PTHREAD)
        queueMicrotask(pump);
      else setTimeout(pump, 0);
    },

    pump: function() {
      if (this.disposed) return;
      for (var session of this.sessions.values()) {
        for (var request of session.requests.values()) {
          if (this.active >= this.limits.parallel) return;
          if (request.state !== 'queued') continue;
          request.state = 'compiling';
          this.active++;
          this.compile(request);
        }
      }
    },

    compile: async function(request) {
      try {
        var module = await WebAssembly.compile(request.bytes);
        request.bytes = null;
        if (!this.live(request)) { this.discarded++; return; }
        // Ordinary and AudioWorklet builds import the exact memory object owned
        // by their main module. The generated module matches its shared flag.
        var instance = await WebAssembly.instantiate(module, {env: {memory: wasmMemory}});
        if (!this.live(request)) { this.discarded++; return; }
        var block = instance.exports.block;
        if (typeof block !== 'function') throw new Error('Missing JIT block export');
        var slot = addFunction(block, 'jii');
        request.slot = slot;
        request.result = slot + 1;
        request.state = 'ready';
        this.compiled++;
      } catch (error) {
        if (this.live(request)) {
          request.bytes = null;
          request.state = 'failed';
          request.result = -1;
          this.failed++;
          this.lastError = String(error);
        }
      } finally {
        this.active--;
        this.schedule();
      }
    },

    poll: function(id, token) {
      var session = this.sessions.get(id);
      var request = session && session.requests.get(token);
      return request ? request.result : -1;
    },

    forget: function(id, token) {
      var session = this.sessions.get(id);
      var request = session && session.requests.get(token);
      if (!request) return;
      // Never unregister during execution of that function. Rust invokes this
      // only before dispatch or when clearing a paused/reset runtime.
      if (request.slot !== null) removeFunction(request.slot);
      request.bytes = null;
      session.bytes -= request.size;
      session.requests.delete(token);
    },

    clear: function(id) {
      var session = this.sessions.get(id);
      if (!session) return;
      session.generation++;
      for (var token of session.requests.keys()) this.forget(id, token);
    },

    release: function(id) {
      this.clear(id);
      this.sessions.delete(id);
    },

    dispose: function() {
      this.disposed = true;
      for (var id of this.sessions.keys()) this.release(id);
    },

    stats: function() {
      var requests = 0, bytes = 0, ready = 0;
      for (var session of this.sessions.values()) {
        requests += session.requests.size;
        bytes += session.bytes;
        for (var request of session.requests.values()) if (request.state === 'ready') ready++;
      }
      return {abi: 4, enabled: Module['dingooWasmJitEnabled'] !== false,
        disposed: this.disposed, shared: this.shared(), sessions: this.sessions.size,
        requests: requests, ready: ready, generatedBytes: bytes, compiling: this.active,
        submitted: this.submitted, compiled: this.compiled, failed: this.failed,
        discarded: this.discarded, lastError: this.lastError};
    }
  },
  dingoo_wasm_jit_set_enabled: function(enabled) { Module['dingooWasmJitEnabled'] = !!enabled; },
  dingoo_wasm_jit_create__deps: ['$DingooWasmJit'],
  dingoo_wasm_jit_create: function() { return DingooWasmJit.create(); },
  dingoo_wasm_jit_shared__deps: ['$DingooWasmJit'],
  dingoo_wasm_jit_shared: function() { return DingooWasmJit.shared() ? 1 : 0; },
  dingoo_wasm_jit_submit__deps: ['$DingooWasmJit'],
  dingoo_wasm_jit_submit: function(id, pointer, length) { return DingooWasmJit.submit(id, pointer, length); },
  dingoo_wasm_jit_poll__deps: ['$DingooWasmJit'],
  dingoo_wasm_jit_poll: function(id, token) { return DingooWasmJit.poll(id, token); },
  dingoo_wasm_jit_forget__deps: ['$DingooWasmJit'],
  dingoo_wasm_jit_forget: function(id, token) { DingooWasmJit.forget(id, token); },
  dingoo_wasm_jit_clear__deps: ['$DingooWasmJit'],
  dingoo_wasm_jit_clear: function(id) { DingooWasmJit.clear(id); },
  dingoo_wasm_jit_release__deps: ['$DingooWasmJit'],
  dingoo_wasm_jit_release: function(id) { DingooWasmJit.release(id); }
});
